// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

type yySymType struct {
	yys      int
	ident    string
	num      string
	args     []string
	expr     Expr
	exprlist []Expr
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57355
	yyEofCode = 57344
	yyErrCode = 57345
	kElse     = 57352
	kEnd      = 57354
	kFunc     = 57353
	kIf       = 57350
	kIn       = 57349
	kLet      = 57348
	kThen     = 57351
	tIdent    = 57346
	tNumber   = 57347

	yyMaxDepth = 200
	yyTabOfs   = -32
)

var (
	yyPrec = map[int]int{
		'<': 0,
		'+': 1,
		'-': 1,
		'*': 2,
		'/': 2,
		'(': 3,
	}

	yyXLAT = map[int]int{
		40:    0,  // '(' (44x)
		41:    1,  // ')' (32x)
		42:    2,  // '*' (28x)
		43:    3,  // '+' (28x)
		45:    4,  // '-' (28x)
		47:    5,  // '/' (28x)
		60:    6,  // '<' (28x)
		44:    7,  // ',' (24x)
		57354: 8,  // kEnd (22x)
		57344: 9,  // $end (20x)
		57352: 10, // kElse (19x)
		57349: 11, // kIn (19x)
		57351: 12, // kThen (19x)
		57365: 13, // ident (18x)
		57346: 14, // tIdent (18x)
		57360: 15, // call (15x)
		57361: 16, // expr (15x)
		57364: 17, // func (15x)
		57366: 18, // if (15x)
		57353: 19, // kFunc (15x)
		57350: 20, // kIf (15x)
		57348: 21, // kLet (15x)
		57367: 22, // let (15x)
		57368: 23, // num (15x)
		57347: 24, // tNumber (15x)
		61:    25, // '=' (2x)
		57356: 26, // arglist0 (1x)
		57357: 27, // arglist1 (1x)
		57358: 28, // args (1x)
		57359: 29, // body (1x)
		57362: 30, // exprlist0 (1x)
		57363: 31, // exprlist1 (1x)
		57369: 32, // top (1x)
		57355: 33, // $default (0x)
		57345: 34, // error (0x)
	}

	yySymNames = []string{
		"'('",
		"')'",
		"'*'",
		"'+'",
		"'-'",
		"'/'",
		"'<'",
		"','",
		"kEnd",
		"$end",
		"kElse",
		"kIn",
		"kThen",
		"ident",
		"tIdent",
		"call",
		"expr",
		"func",
		"if",
		"kFunc",
		"kIf",
		"kLet",
		"let",
		"num",
		"tNumber",
		"'='",
		"arglist0",
		"arglist1",
		"args",
		"body",
		"exprlist0",
		"exprlist1",
		"top",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {32, 1},
		2:  {16, 1},
		3:  {16, 1},
		4:  {16, 3},
		5:  {16, 3},
		6:  {16, 3},
		7:  {16, 3},
		8:  {16, 3},
		9:  {16, 3},
		10: {16, 1},
		11: {22, 7},
		12: {16, 1},
		13: {18, 7},
		14: {16, 1},
		15: {17, 6},
		16: {28, 1},
		17: {29, 1},
		18: {26, 0},
		19: {26, 1},
		20: {26, 2},
		21: {27, 1},
		22: {27, 3},
		23: {16, 1},
		24: {15, 4},
		25: {30, 0},
		26: {30, 1},
		27: {30, 2},
		28: {31, 1},
		29: {31, 3},
		30: {13, 1},
		31: {23, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [57][]uint8{
		// 0
		{37, 13: 35, 45, 44, 34, 42, 40, 43, 41, 39, 38, 36, 46, 32: 33},
		{9: 32},
		{63, 2: 61, 59, 60, 62, 58, 9: 31},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30},
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29},
		// 5
		{37, 13: 35, 45, 44, 87, 42, 40, 43, 41, 39, 38, 36, 46},
		{22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22},
		{13: 81, 45},
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20},
		{37, 13: 35, 45, 44, 75, 42, 40, 43, 41, 39, 38, 36, 46},
		// 10
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18},
		{47},
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
		{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 25: 2},
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
		// 15
		{1: 14, 13: 51, 45, 26: 49, 50, 48},
		{1: 54},
		{1: 16},
		{1: 13, 7: 52},
		{1: 11, 7: 11},
		// 20
		{1: 12, 13: 53, 45},
		{1: 10, 7: 10},
		{37, 13: 35, 45, 44, 55, 42, 40, 43, 41, 39, 38, 36, 46, 29: 56},
		{63, 2: 61, 59, 60, 62, 58, 8: 15},
		{8: 57},
		// 25
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17},
		{37, 13: 35, 45, 44, 74, 42, 40, 43, 41, 39, 38, 36, 46},
		{37, 13: 35, 45, 44, 73, 42, 40, 43, 41, 39, 38, 36, 46},
		{37, 13: 35, 45, 44, 72, 42, 40, 43, 41, 39, 38, 36, 46},
		{37, 13: 35, 45, 44, 71, 42, 40, 43, 41, 39, 38, 36, 46},
		// 30
		{37, 13: 35, 45, 44, 70, 42, 40, 43, 41, 39, 38, 36, 46},
		{37, 7, 13: 35, 45, 44, 64, 42, 40, 43, 41, 39, 38, 36, 46, 30: 65, 66},
		{63, 4, 61, 59, 60, 62, 58, 4},
		{1: 69},
		{1: 6, 7: 67},
		// 35
		{37, 5, 13: 35, 45, 44, 68, 42, 40, 43, 41, 39, 38, 36, 46},
		{63, 3, 61, 59, 60, 62, 58, 3},
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
		{63, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23},
		{63, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24},
		// 40
		{63, 25, 61, 25, 25, 62, 25, 25, 25, 25, 25, 25, 25},
		{63, 26, 61, 26, 26, 62, 26, 26, 26, 26, 26, 26, 26},
		{63, 27, 61, 59, 60, 62, 27, 27, 27, 27, 27, 27, 27},
		{63, 2: 61, 59, 60, 62, 58, 12: 76},
		{37, 13: 35, 45, 44, 77, 42, 40, 43, 41, 39, 38, 36, 46},
		// 45
		{63, 2: 61, 59, 60, 62, 58, 10: 78},
		{37, 13: 35, 45, 44, 79, 42, 40, 43, 41, 39, 38, 36, 46},
		{63, 2: 61, 59, 60, 62, 58, 8: 80},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19},
		{25: 82},
		// 50
		{37, 13: 35, 45, 44, 83, 42, 40, 43, 41, 39, 38, 36, 46},
		{63, 2: 61, 59, 60, 62, 58, 11: 84},
		{37, 13: 35, 45, 44, 85, 42, 40, 43, 41, 39, 38, 36, 46},
		{63, 2: 61, 59, 60, 62, 58, 8: 86},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21},
		// 55
		{63, 88, 61, 59, 60, 62, 58},
		{28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 34

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*lexer).result = yyS[yypt-0].expr
		}
	case 2:
		{
			yyVAL.expr = &VarExpr{yyS[yypt-0].ident}
		}
	case 3:
		{
			yyVAL.expr = &IntExpr{yyS[yypt-0].num}
		}
	case 4:
		{
			yyVAL.expr = yyS[yypt-1].expr
		}
	case 5:
		{
			yyVAL.expr = &BinExpr{"<", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 6:
		{
			yyVAL.expr = &BinExpr{"+", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 7:
		{
			yyVAL.expr = &BinExpr{"-", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 8:
		{
			yyVAL.expr = &BinExpr{"*", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 9:
		{
			yyVAL.expr = &BinExpr{"/", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 11:
		{
			yyVAL.expr = &LetExpr{Var: yyS[yypt-5].ident, Val: yyS[yypt-3].expr, Body: yyS[yypt-1].expr}
		}
	case 13:
		{
			yyVAL.expr = &IfExpr{yyS[yypt-5].expr, yyS[yypt-3].expr, yyS[yypt-1].expr}
		}
	case 15:
		{
			yyVAL.expr = &FuncExpr{"", yyS[yypt-3].args, yyS[yypt-1].expr}
		}
	case 18:
		{
			yyVAL.args = nil
		}
	case 21:
		{
			yyVAL.args = []string{yyS[yypt-0].ident}
		}
	case 22:
		{
			yyVAL.args = append(yyS[yypt-2].args, yyS[yypt-0].ident)
		}
	case 24:
		{
			yyVAL.expr = &CallExpr{Func: yyS[yypt-3].expr, Args: yyS[yypt-1].exprlist}
		}
	case 25:
		{
			yyVAL.exprlist = nil
		}
	case 28:
		{
			yyVAL.exprlist = []Expr{yyS[yypt-0].expr}
		}
	case 29:
		{
			yyVAL.exprlist = append(yyS[yypt-2].exprlist, yyS[yypt-0].expr)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
