// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

type yySymType struct {
	yys      int
	ident    string
	num      string
	args     []string
	expr     Expr
	exprlist []Expr
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57358
	yyEofCode = 57344
	yyErrCode = 57345
	kAnd      = 57355
	kElse     = 57352
	kEnd      = 57354
	kFunc     = 57353
	kIf       = 57350
	kIn       = 57349
	kLet      = 57348
	kOr       = 57356
	kThen     = 57351
	tIdent    = 57346
	tNumber   = 57347
	unary     = 57357

	yyMaxDepth = 200
	yyTabOfs   = -41
)

var (
	yyPrec = map[int]int{
		kAnd:  0,
		kOr:   0,
		'<':   1,
		'>':   1,
		'=':   1,
		'+':   2,
		'-':   2,
		'*':   3,
		'/':   3,
		unary: 4,
		'(':   5,
		'.':   6,
	}

	yyXLAT = map[int]int{
		40:    0,  // '(' (62x)
		45:    1,  // '-' (60x)
		41:    2,  // ')' (43x)
		61:    3,  // '=' (41x)
		42:    4,  // '*' (37x)
		43:    5,  // '+' (37x)
		46:    6,  // '.' (37x)
		47:    7,  // '/' (37x)
		60:    8,  // '<' (37x)
		62:    9,  // '>' (37x)
		57355: 10, // kAnd (37x)
		57356: 11, // kOr (37x)
		44:    12, // ',' (33x)
		57354: 13, // kEnd (32x)
		57344: 14, // $end (29x)
		57346: 15, // tIdent (29x)
		57368: 16, // ident (28x)
		57352: 17, // kElse (28x)
		57349: 18, // kIn (28x)
		57351: 19, // kThen (28x)
		57363: 20, // call (23x)
		57364: 21, // expr (23x)
		57367: 22, // func (23x)
		57369: 23, // if (23x)
		57353: 24, // kFunc (23x)
		57350: 25, // kIf (23x)
		57348: 26, // kLet (23x)
		57370: 27, // let (23x)
		57371: 28, // num (23x)
		57347: 29, // tNumber (23x)
		57359: 30, // arglist0 (2x)
		57360: 31, // arglist1 (2x)
		57361: 32, // args (2x)
		57362: 33, // body (2x)
		57365: 34, // exprlist0 (1x)
		57366: 35, // exprlist1 (1x)
		57372: 36, // top (1x)
		57358: 37, // $default (0x)
		57345: 38, // error (0x)
		57357: 39, // unary (0x)
	}

	yySymNames = []string{
		"'('",
		"'-'",
		"')'",
		"'='",
		"'*'",
		"'+'",
		"'.'",
		"'/'",
		"'<'",
		"'>'",
		"kAnd",
		"kOr",
		"','",
		"kEnd",
		"$end",
		"tIdent",
		"ident",
		"kElse",
		"kIn",
		"kThen",
		"call",
		"expr",
		"func",
		"if",
		"kFunc",
		"kIf",
		"kLet",
		"let",
		"num",
		"tNumber",
		"arglist0",
		"arglist1",
		"args",
		"body",
		"exprlist0",
		"exprlist1",
		"top",
		"$default",
		"error",
		"unary",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {36, 1},
		2:  {21, 1},
		3:  {21, 1},
		4:  {21, 3},
		5:  {21, 3},
		6:  {21, 3},
		7:  {21, 3},
		8:  {21, 4},
		9:  {21, 4},
		10: {21, 4},
		11: {21, 3},
		12: {21, 3},
		13: {21, 3},
		14: {21, 3},
		15: {21, 3},
		16: {21, 3},
		17: {21, 2},
		18: {21, 1},
		19: {27, 7},
		20: {21, 1},
		21: {23, 7},
		22: {21, 1},
		23: {22, 6},
		24: {22, 7},
		25: {32, 1},
		26: {33, 1},
		27: {30, 0},
		28: {30, 1},
		29: {30, 2},
		30: {31, 1},
		31: {31, 3},
		32: {21, 1},
		33: {20, 4},
		34: {34, 0},
		35: {34, 1},
		36: {34, 2},
		37: {35, 1},
		38: {35, 3},
		39: {16, 1},
		40: {28, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [80][]uint8{
		// 0
		{46, 47, 15: 55, 44, 20: 54, 43, 52, 50, 53, 51, 49, 48, 45, 56, 36: 42},
		{14: 41},
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 14: 40},
		{39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 17: 39, 39, 39},
		{38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 17: 38, 38, 38},
		// 5
		{46, 47, 15: 55, 44, 20: 54, 119, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 15: 55, 44, 20: 54, 118, 52, 50, 53, 51, 49, 48, 45, 56},
		{23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 17: 23, 23, 23},
		{15: 55, 112},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 17: 21, 21, 21},
		// 10
		{46, 47, 15: 55, 44, 20: 54, 106, 52, 50, 53, 51, 49, 48, 45, 56},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 17: 19, 19, 19},
		{57, 15: 58},
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 17: 9, 9, 9},
		{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 17: 2, 2, 2},
		// 15
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 17: 1, 1, 1},
		{2: 14, 15: 55, 63, 30: 61, 62, 102},
		{59},
		{2: 14, 15: 55, 63, 30: 61, 62, 60},
		{2: 66},
		// 20
		{2: 16},
		{2: 13, 12: 64},
		{2: 11, 12: 11},
		{2: 12, 15: 55, 65},
		{2: 10, 12: 10},
		// 25
		{46, 47, 15: 55, 44, 20: 54, 67, 52, 50, 53, 51, 49, 48, 45, 56, 33: 68},
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 13: 15},
		{13: 69},
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17: 17, 17, 17},
		{46, 47, 15: 55, 44, 20: 54, 101, 52, 50, 53, 51, 49, 48, 45, 56},
		// 30
		{46, 47, 15: 55, 44, 20: 54, 100, 52, 50, 53, 51, 49, 48, 45, 56},
		{15: 55, 99},
		{3: 97},
		{46, 47, 3: 95, 15: 55, 44, 20: 54, 94, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 3: 92, 15: 55, 44, 20: 54, 91, 52, 50, 53, 51, 49, 48, 45, 56},
		// 35
		{46, 47, 15: 55, 44, 20: 54, 90, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 15: 55, 44, 20: 54, 89, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 15: 55, 44, 20: 54, 88, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 15: 55, 44, 20: 54, 87, 52, 50, 53, 51, 49, 48, 45, 56},
		{46, 47, 7, 15: 55, 44, 20: 54, 81, 52, 50, 53, 51, 49, 48, 45, 56, 34: 82, 83},
		// 40
		{80, 77, 4, 73, 78, 76, 72, 79, 74, 75, 70, 71, 4},
		{2: 86},
		{2: 6, 12: 84},
		{46, 47, 5, 15: 55, 44, 20: 54, 85, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 3, 73, 78, 76, 72, 79, 74, 75, 70, 71, 3},
		// 45
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 17: 8, 8, 8},
		{80, 25, 25, 25, 25, 25, 72, 25, 25, 25, 25, 25, 25, 25, 25, 17: 25, 25, 25},
		{80, 26, 26, 26, 26, 26, 72, 26, 26, 26, 26, 26, 26, 26, 26, 17: 26, 26, 26},
		{80, 27, 27, 27, 78, 27, 72, 79, 27, 27, 27, 27, 27, 27, 27, 17: 27, 27, 27},
		{80, 28, 28, 28, 78, 28, 72, 79, 28, 28, 28, 28, 28, 28, 28, 17: 28, 28, 28},
		// 50
		{80, 77, 29, 29, 78, 76, 72, 79, 29, 29, 29, 29, 29, 29, 29, 17: 29, 29, 29},
		{46, 47, 15: 55, 44, 20: 54, 93, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 31, 31, 78, 76, 72, 79, 31, 31, 31, 31, 31, 31, 31, 17: 31, 31, 31},
		{80, 77, 30, 30, 78, 76, 72, 79, 30, 30, 30, 30, 30, 30, 30, 17: 30, 30, 30},
		{46, 47, 15: 55, 44, 20: 54, 96, 52, 50, 53, 51, 49, 48, 45, 56},
		// 55
		{80, 77, 32, 32, 78, 76, 72, 79, 32, 32, 32, 32, 32, 32, 32, 17: 32, 32, 32},
		{46, 47, 15: 55, 44, 20: 54, 98, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 33, 33, 78, 76, 72, 79, 33, 33, 33, 33, 33, 33, 33, 17: 33, 33, 33},
		{34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17: 34, 34, 34},
		{80, 77, 35, 73, 78, 76, 72, 79, 74, 75, 35, 35, 35, 35, 35, 17: 35, 35, 35},
		// 60
		{80, 77, 36, 73, 78, 76, 72, 79, 74, 75, 36, 36, 36, 36, 36, 17: 36, 36, 36},
		{2: 103},
		{46, 47, 15: 55, 44, 20: 54, 67, 52, 50, 53, 51, 49, 48, 45, 56, 33: 104},
		{13: 105},
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17: 18, 18, 18},
		// 65
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 19: 107},
		{46, 47, 15: 55, 44, 20: 54, 108, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 17: 109},
		{46, 47, 15: 55, 44, 20: 54, 110, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 13: 111},
		// 70
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17: 20, 20, 20},
		{3: 113},
		{46, 47, 15: 55, 44, 20: 54, 114, 52, 50, 53, 51, 49, 48, 45, 56},
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 18: 115},
		{46, 47, 15: 55, 44, 20: 54, 116, 52, 50, 53, 51, 49, 48, 45, 56},
		// 75
		{80, 77, 3: 73, 78, 76, 72, 79, 74, 75, 70, 71, 13: 117},
		{22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 17: 22, 22, 22},
		{80, 24, 24, 24, 24, 24, 72, 24, 24, 24, 24, 24, 24, 24, 24, 17: 24, 24, 24},
		{80, 77, 120, 73, 78, 76, 72, 79, 74, 75, 70, 71},
		{37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 17: 37, 37, 37},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 38

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*lexer).result = yyS[yypt-0].expr
		}
	case 2:
		{
			yyVAL.expr = &VarExpr{yyS[yypt-0].ident}
		}
	case 3:
		{
			yyVAL.expr = &IntExpr{yyS[yypt-0].num}
		}
	case 4:
		{
			yyVAL.expr = yyS[yypt-1].expr
		}
	case 5:
		{
			yyVAL.expr = &AndExpr{yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 6:
		{
			yyVAL.expr = &OrExpr{yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 7:
		{
			yyVAL.expr = &DotExpr{".", yyS[yypt-2].expr, yyS[yypt-0].ident}
		}
	case 8:
		{
			yyVAL.expr = &BinExpr{"eq", yyS[yypt-3].expr, yyS[yypt-0].expr}
		}
	case 9:
		{
			yyVAL.expr = &BinExpr{"<=", yyS[yypt-3].expr, yyS[yypt-0].expr}
		}
	case 10:
		{
			yyVAL.expr = &BinExpr{">=", yyS[yypt-3].expr, yyS[yypt-0].expr}
		}
	case 11:
		{
			yyVAL.expr = &BinExpr{"<", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 12:
		{
			yyVAL.expr = &BinExpr{">", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 13:
		{
			yyVAL.expr = &BinExpr{"+", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 14:
		{
			yyVAL.expr = &BinExpr{"-", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 15:
		{
			yyVAL.expr = &BinExpr{"*", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 16:
		{
			yyVAL.expr = &BinExpr{"/", yyS[yypt-2].expr, yyS[yypt-0].expr}
		}
	case 17:
		{
			yyVAL.expr = &BinExpr{"-", &IntExpr{"0"}, yyS[yypt-0].expr}
		}
	case 19:
		{
			yyVAL.expr = &LetExpr{Var: yyS[yypt-5].ident, Val: yyS[yypt-3].expr, Body: yyS[yypt-1].expr}
		}
	case 21:
		{
			yyVAL.expr = &IfExpr{yyS[yypt-5].expr, yyS[yypt-3].expr, yyS[yypt-1].expr}
		}
	case 23:
		{
			yyVAL.expr = &FuncExpr{"", yyS[yypt-3].args, yyS[yypt-1].expr}
		}
	case 24:
		{
			yyVAL.expr = &FuncExpr{yyS[yypt-5].ident, yyS[yypt-3].args, yyS[yypt-1].expr}
		}
	case 27:
		{
			yyVAL.args = nil
		}
	case 30:
		{
			yyVAL.args = []string{yyS[yypt-0].ident}
		}
	case 31:
		{
			yyVAL.args = append(yyS[yypt-2].args, yyS[yypt-0].ident)
		}
	case 33:
		{
			yyVAL.expr = &CallExpr{Func: yyS[yypt-3].expr, Args: yyS[yypt-1].exprlist}
		}
	case 34:
		{
			yyVAL.exprlist = nil
		}
	case 37:
		{
			yyVAL.exprlist = []Expr{yyS[yypt-0].expr}
		}
	case 38:
		{
			yyVAL.exprlist = append(yyS[yypt-2].exprlist, yyS[yypt-0].expr)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
